stages:          # List of stages for jobs, and their order of execution
  - linting
  - doc
  - light-testing
  - heavy-testing
  - release

default:
    image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:gallium-alpine3.15

lint-job:
    stage: linting
    before_script:
        - echo 'Performing lint-job...'
        - npm install eslint --save-dev
    script:
        - npm run lint
    after_script:
        - echo 'lint-job is done !'

doc-coverage-job:
    stage: doc
    script:
        - echo todo
        - 'false'

unit-test-job:
    image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:gallium-alpine3.15
    stage: light-testing
    before_script:
        - npm install --frozen-lockfile
    script:
        - npm run coverage
        - npm run report
        - npm run report-coverage
    coverage: /All files\s*\|\s*([\d\.]+)/
    artifacts:
        when: always
        reports:
            junit:
                - junit.xml
            cobertura: coverage/cobertura-coverage.xml

funct-testing:
    stage: heavy-testing
    script:
        - echo todo
        - 'false'

bundle-code-job:
    stage: release
    before_script:
        - npm install --frozen-lockfile
    script:
        - npm run build


bundle-doc-job:
    stage: release
    script:
        - echo todo
        - 'false'


